-- CreateTable
CREATE TABLE "USUARIO" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "nome" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "senha" TEXT NOT NULL,
    "cargo" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "ESTOQUE" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "nome" TEXT NOT NULL,
    "descricao" TEXT,
    "quantidade" INTEGER NOT NULL DEFAULT 0,
    "preco" REAL NOT NULL
);

-- CreateTable
CREATE TABLE "MOVIMENTACAO" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "tipo" TEXT NOT NULL,
    "quantidade" INTEGER NOT NULL,
    "valor" REAL NOT NULL,
    "criado_em" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "estoqueId" INTEGER NOT NULL,
    "usuarioId" INTEGER NOT NULL,
    CONSTRAINT "MOVIMENTACAO_estoqueId_fkey" FOREIGN KEY ("estoqueId") REFERENCES "ESTOQUE" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "MOVIMENTACAO_usuarioId_fkey" FOREIGN KEY ("usuarioId") REFERENCES "USUARIO" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX "USUARIO_email_key" ON "USUARIO"("email");
